### ISSUE TITLE
Importing package on unity 2021.3.1f1c1 cause multiple error

### ISSUE THREAD

**Issue by OU2018** [AndrewLnk/LiveShapes#1]
A large number of error prompts of missing prefeb appear when opening demo scene; And the .ls file cannot be loaded in Live Shapes>editor.
GlobalPostProcessingProfile And Example>New Folder>New Post-processing Profile Missing Script.

**Comment by AndrewLnk** [comment]
Thank you!
Fixed in the last commit.

Commit:
_[FIXED] Importing package on unity 2021.3.1f1c1 cause multiple error_
